"""Add user ownership to applications

Revision ID: 27b5c45f87c5
Revises: 03ec6002fa81
Create Date: 2026-10-06 18:02:55.945291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b5c45f87c5'
down_revision: Union[str, Sequence[str], None] = '03ec6002fa81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'user_id')
    # ### end Alembic commands ###
